### PR TITLE
feat: android dialog buttons text color

### PR DESCRIPTION
**Pull request by vonovak**
# Summary

follow up on https://github.com/react-native-datetimepicker/datetimepicker/pull/680 this PR allows setting button color dynamically from JS - android only

## Test Plan

tested locally 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅      |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 6.6.0 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:

**Comment by thespacemanatee** [comment]
@vonovak did you forget to `import com.facebook.react.bridge.Arguments;` in `RNDatePickerDialogModule`? I had to manually patch it.

**Comment by vonovak** [comment]
@thespacemanatee no, that import should be covered here: https://github.com/react-native-datetimepicker/datetimepicker/blob/a64219f44587a38a4e21023cd12f1d4353bfeb70/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java#L21


the code has passed through [CI](https://app.circleci.com/pipelines/github/react-native-datetimepicker/datetimepicker/1097/workflows/c2fed20e-53a0-4ec2-822c-f59a25ffb993/jobs/3409) so I believe everything is okay on the library side 🙂

**Comment by thespacemanatee** [comment]
@vonovak weird, the build is failing locally and on EAS servers, will do some more investigating but reverting to `6.5.0` for now!

**Pull request merged**
