### PR TITLE
fix: do not update android dialog on each re-render

### LINKED ISSUE #182: Android: DateTimePicker keeps resetting to default value
My DateTimePicker keeps resetting to the default value while open.

Code:

```
const CustomDateTimePicker = React.memo((onChange) => {

    console.log('Rerender CustomDateTimePicker');

    const [date, setDate] = useState(new Date('1985/01/01'));
    const [show, setShow] = useState(Platform.OS === 'ios');

    const onDateChange = useCallback((event, date) => {
        setShow(Platform.OS === 'ios');
        setDate(date);
        onChange(date);
    }, []);

    useEffect(() => {
        console.log('Date changed');
    }, [date]);

    return (
        <View style={{ flexDirection: 'row' }}>
            {Platform.OS === 'android' &&
                <TouchableOpacity
                    onPress={() => setShow(true)}
                    style={{
                        flex: 1,
                        marginVertical: 10,
                        padding: 10,
                    }}
                >
                    <Text style={{ fontSize: 16 }}>{date && date.toLocaleDateString()}</Text>
                </TouchableOpacity>
            }
            {show &&
                <DateTimePicker
                    testID="dateTimePicker"
                    textColor={'#ffffff'}
                    value={date}
                    mode={'date'}
                    display='default'
                    onChange={onDateChange}
                />
            }
        </View>
    )
});

export default CustomDateTimePicker;
```

When the dialog is open and I select a date, the component will undo my change and go back to the default value after a second or two.

I don't the console prints while this is happening.

### LINKED ISSUE #235: Value is being updated while picking
**_The problem:_**
`value` props is being updated, even if picker is open. The use case is below.

**_The component:_**
```jsx
function MyComponent ({ onChange, mode }) {
  const [value, setValue] = useState(new Date());

  useEffect(() => {
     setTimeout(() => setValue(new Date(+ value + 60 * 60 * 1000)), 5000);
   }, []);

  return (
    <DateTimePicker
    value={value}
    mode={mode}
    onChange={onChange}
  />
  );
}
```

**_The scenario:_**
1. `<MyComponent mode="time" onChange={...} />` is rendered
2. During first 3 seconds, pick hours and wait on minutes screen
3. Wait another 2 seconds
4. Selected hours suddenly has been changed

## Environment info

Tested only on **Android**

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.55 GB / 15.85 GB
  Binaries:
    Node: 12.18.0 - ~\AppData\Local\Temp\yarn--1596125151497-0.3420221356958104\node.CMD
    Yarn: 1.22.4 - ~\AppData\Local\Temp\yarn--1596125151497-0.3420221356958104\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: Not Found
    Python: 2.7.16 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ~0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.6.1

### PR DESCRIPTION
**Pull request by vonovak**
# Summary

replacement for #327, please see motivation there. To sum it up, android dialog's selected date is controlled from JS and while the dialog is open, it will update only if the date changed in JS

Closes #182
Closes #235
Closes #327

 

## Test Plan

tested locally

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅      |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Review by liuspatt — APPROVED** [review]

**Review by luancurti — APPROVED** [review]
Sorry for the delay

Great Job! 🎉

**Comment by vonovak** [comment]
@luancurti can you please check discord? I left a message in the datepicker channel, thank you! :)

**Comment by snios** [comment]
Just tested this new version that is supposed to not update on re-render. But it does not work for me atleast. I have a useEffect with setInterval that triggers a recalculation of time once each second. And the datepicker reverts my date while open and selecting, every time my value is recalculated. My picker is inside a modal.

**Comment by vonovak** [comment]
@snios that is the expected behavior:

> To sum it up, android dialog's selected date is controlled from JS and while the dialog is open, it will update only if the date changed in JS

**Comment by snios** [comment]
> @snios that is the expected behavior, JS is the source of truth for the picker:
> 
> > To sum it up, android dialog's selected date is controlled from JS and while the dialog is open, it will update only if the date changed in JS

Hm. I dont change the js date that the picker uses as far as i know. The calculation that is done in useeffect is not connected with the date. The date picker is a separate component that houses its own logic.

**Comment by AmolFC** [comment]
@snios We are also facing same problem in our code. Did you find solution for same?

**Comment by snios** [comment]
> @snios We are also facing same problem in our code. Did you find solution for same?

Hi. Issue for us was that in the parent view of the modal there was a setInterval that calculated som values and that made the modal component reinitialize (the constructor ran again). So in the view that  has the setInterval i dont recalculate the values if modal is shown. Probably a bad solution but it works.

example.
`  useEffect(() => {
    if(modalVisible == false){
      const tickerID = setInterval(() => {
        calculateTimers();
      }, 1000);
      return () => clearInterval(tickerID);
    }
   });`

**Pull request merged**
