### PR TITLE
Add visual studio 2022 support

### PR DESCRIPTION
**Pull request by E-Palmer**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅ ❌     |
| Android |    ✅ ❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
@rectified95 would you please review the PR? It's super short. Many thanks :)

**Comment by rectified95** [comment]
@chiaramooney @AgneLukoseviciute - mind taking a look if this is enough to enable VS2022?

**Comment by chiaramooney** [comment]
@vonovak React Native Windows itself doesn't support VS 2022 yet, so we wouldn't recommend having the module support it while the platform doesn't. Could be something to revisit after RNW moves to VS2022.

**Comment by vonovak** [comment]
closing as per the comment above. I believe MS folks will get back to this when needed.
thank you!

**Pull request closed without merging**
