### PR TITLE
Ignore node version on yarn install

### PR DESCRIPTION
**Pull request by luancurti**
# Summary

Ignore node version on yarn install

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅ ❌     |
| Android |    ✅ ❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
I'm going to assume this fixes the publish step of pipeline.. :)

**Review by vonovak — APPROVED** [review]

**Comment by vonovak** [comment]
thanks for fixing this @luancurti ! :)

**Comment by luancurti** [comment]
> I'm going to assume this fixes the publish step of pipeline.. :)

that's right

**Pull request merged**
