### PR TITLE
feat: Allow overriding theme variant used by native ios picker

### PR DESCRIPTION
**Pull request by AmauryLiet**
# Summary

For iOS apps that:
- made the decision of a light/dark UI regardless of system preferences
- or allow user to change theme manually in some settings,

the picker is challenging to integrate in spinner+inline modes, since text is likely to be white-on-white or dark-or-dark.

As demonstrated here:

- inline
inline
- spinner
spinner

⚠️ this will only work on iOS 13+ due to the use of `setOverrideUserInterfaceStyle`. For iOS 12-, one can only use "spinner" mode, and can use the existing `textColor` to have a convenient UI

## Test Plan

Tested on:
- iOS 14.5.1 real device
- iOS 12.4 simulator

In cases:
- prop `themeVariant="light"` and system light
- prop `themeVariant="light"` and system dark
- prop `themeVariant="dark"` and system light
- prop `themeVariant="dark"` and system dark
- prop `themeVariant` unset and system light
- prop `themeVariant` unset and system dark

### What's required for testing (prerequisites)?

N/A

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅      |
| Android |    ❌      |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

Related:
- #308 (doesn't adress the issue but will solve it in some use cases)
- #20 (doesn't adress the issue but will solve it in some use cases)
Fixes:
- #296

### CODE REVIEW

**Review by vonovak — APPROVED** [review]
thanks, this looks perfect! 👍 

would you be interested in becoming a collaborator? 🙂

**Comment by vonovak** [comment]
For some weird reason, Circle ci is not building the branch. Can you try pushing something in it to see if circle wakes up? Thanks :)

**Comment by AmauryLiet** [comment]
> thanks, this looks perfect! 👍
> 
> would you be interested in becoming a collaborator? 🙂

Hey @vonovak, thanks for the proposal! I am not 100% confident that I am going to use the lib intensively in the coming weeks/months, but I would be happy to make some contribution in my spare time :)

**Comment by AmauryLiet** [comment]
> For some weird reason, Circle ci is not building the branch. Can you try pushing something in it to see if circle wakes up? Thanks :)

tryed to re-trigger without success, could you open a branch on your side to see if the issue is limited to this PR?

**Comment by vonovak** [comment]
hello again!

Building from a fork should work. I got in touch with circle support to see if they have something to say about this. In the meantime, I'll try to check out a new branch and cherry pick your commits.

> thanks for the proposal! I am not 100% confident that I am going to use the lib intensively in the coming weeks/months, but I would be happy to make some contribution in my spare time :)

perfect, yes, it's all up to you how much or how little you want to get involved :) I just sent you an invite! :)

**Pull request merged**
