### PR TITLE
fix circle ci status badge according new org

### PR DESCRIPTION
**Pull request by luancurti**
# Summary

fix circle ci status badge according new org

## Test Plan

The badge should show the build status from circle ci

Screen Shot 2020-09-29 at 20 17 50

## Checklist

- [ ] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
hello, and thanks! Why is it showing a "passed" icon (see https://github.com/react-native-datetimepicker/datetimepicker/tree/fix/circle-ci-build-badge) when in fact, the pipeline did not pass..?

**Comment by luancurti** [comment]
> hello, and thanks! Why is it showing a "passed" icon (see https://github.com/react-native-datetimepicker/datetimepicker/tree/fix/circle-ci-build-badge) when in fact, the pipeline did not pass..?

I think the last two builds the circle ci is considering `not run` and the `last` build that `that ran` **passed**  

Screen Shot 2020-09-30 at 12 50 51

**Comment by luancurti** [comment]
@vonovak what type of badge we should use? 

`svg` 
Screen Shot 2020-09-29 at 20 17 50

or

`shield`
Screen Shot 2020-09-30 at 12 56 02

**Review by vonovak — APPROVED** [review]

**Pull request merged**
