### PR TITLE
Update RNDateTimePickerShadowView.m

### LINKED ISSUE #866: When running in Xcode 15.3 getting Incompatible function pointer types passing 'YGSize (...)' exception
# Bug report

I've updated to the most recent Xcode 15.3 and build started to fail with:
```
Incompatible function pointer types passing 'YGSize (YGNodeRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')
```
Any idea what can be wrong with it?

Getting the issue 
image

```
    "react-native": "0.73.1",
    "@react-native-community/datetimepicker": "^7.6.2",
```

### PR DESCRIPTION
**Pull request by bmichotte**
# Summary
This PR fixes #866 as suggested by @sbeigel in https://github.com/react-native-datetimepicker/datetimepicker/issues/866#issuecomment-1980375427

## Test Plan
Build a RN app with xcode 15.3, you'll receive the error shown in #886

### What are the steps to reproduce (after prerequisites)?
Build in xcode 15.3

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅      |
| Android |     ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by rahie-works** [comment]
@bmichotte I tried mocking this fix in my local to build an RN App in iOS 17.0.1. But I got these errors. Are these related?

Screenshot 2024-03-06 at 2 52 11 PM

**Comment by rahie-works** [comment]
> @bmichotte I tried mocking this fix in my local to build an RN App in iOS 17.0.1. But I got these errors. Are these related?
> 
> Screenshot 2024-03-06 at 2 52 11 PM

Please disregard:
This was fixed from here https://github.com/itinance/react-native-sha256/commit/77af2681181cd2e31e46d57909ec302f14ee24fb

**Comment by jzaefferer** [comment]
Thx! This patch worked for me.

We'll apply it locally for now with `npx patch-package @react-native-community/datetimepicker`

**Comment by f0ntana** [comment]
Tks u!! 
This worked for me too!
Please merge it.

**Review by craigt672 — APPROVED** [review]

**Review by ottaviano — APPROVED** [review]
👍

**Review by OverGlass — APPROVED** [review]
LGTM

**Comment by Robert27** [comment]
Is there any reason why this is not merged yet?

**Comment by fellipe-ribeiro** [comment]
Failed an automatic test.

I think it should be manually analyzed/approved and merged asap

**Review by Robert27 — APPROVED** [review]

**Comment by fnazarios** [comment]
Can we merge this asap?

**Comment by Robert27** [comment]
Is this repo still maintained?

**Comment by f0ntana** [comment]
@luancurti @vonovak 
Hi guys, 
Could we have some attention here? tks.

**Comment by vonovak** [comment]
Hello,
sorry for taking the time. The automated tests are failing, as you can see. We run automated tests in order to ensure the quality of what we're shipping.
What needs to happen is that someone needs to look into the problem; probably run the tests locally and probably update some dependencies like Detox / React Native / ... and maybe update the pipeline so that it runs on latest Xcode.

Do we have a volunteer here? 🙂 Alternatively, I'm happy to look into it but I'd really like to see some companies that use this module to step up and contribute some funds to the maintenance. Right now, the budget is [$5 per month](https://opencollective.com/react-native-datetimepicker) for a package that currently has 461 392 weekly downloads(!!).  I explained my stance in #313.
Thank you and sorry for being that guy.

**Comment by ottaviano** [comment]
Hi @vonovak,
Firstly, thanks a lot for your contribution to this library. I've noticed the CI for this PR is failing for the same reason the master branch's CI fails, indicating the issue isn't related to this PR specifically. Given the changes made here, particularly the fix to the type hint of the first argument, it seems important to merge this to address the significant bug affecting the library.

**Comment by vonovak** [comment]
hi @ottaviano,
thanks for your comment. I didn't mean to imply that the CI failure is related to this change. If you look at the master branch history, you'll see it started failing for a reason that appears to be outside of this repository. In a pipeline that ran on the 15th of February, the e2e testing step passed okay (the publish step failed, but that's a different problem related to expired npm auth token, and I'm working on that). Something has changed in the mean time.

It doesn't happen often that stuff which worked previously would stop working, but it happened here. And, someone needs to do the work of fixing it (or disabling the pipeline checks, so that they are effectively ignored. That, however, would lead us down a slippery slope. Does anyone think disabling pipeline checks is a good idea?)

Even if I force-merge this PR, the change will not be released because the automated release depends on all pipeline steps completing successfully.

There is a known workaround using patch-package in people consuming the package. The way I see it, people should use patch-package until we have all checks green. I'm sorry 🤷‍♂️ .

**Comment by bmichotte** [comment]
Hello @vonovak, a quick search guided me to https://github.com/wix/Detox/issues/4148 which is the same error. 

The error on the android is related to a test killed after 1 hour since it took over than 40 minutes to start the emulator.
> Try out a larger resource class or running tests in parallel to speed up job execution.  Upgrade your pricing plan to take advantage of longer max job runtimes.
> context deadline exceeded

As described in the Detox issue, updating Detox fix the issue, and therefore the iOS CI passes. I guess you can now merge this PR and release it :)

**Comment by vonovak** [comment]
thank you for taking the initiative! 🙂

**Comment by ottaviano** [comment]
yeah! thanks to you two 🤝

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 7.6.3 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:

**Pull request merged**
