### PR TITLE
Fix for RN spinner

### PR DESCRIPTION
**Pull request by billnbell**
https://github.com/react-native-datetimepicker/datetimepicker/issues/411

This fixes the issue for me. It shows spinner on time. I think when Build.VERSION_CODES.N  came it it made sense to use ==, but now there are a ton of newer versions.

`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && display == RNDatePickerDisplay.SPINNER) {`

### CODE REVIEW

**Comment by vonovak** [comment]
hello @billnbell would you mind cleaning up the git history a little so it's clear I'm not merging 24 commits but just 1 commit? Thank you! 👍

**Comment by vonovak** [comment]
@billnbell btw I just invited you to the organization, when you accept the invitation you won't need to use forks and will be able to close issues and etc. Thank you for your contributions! :)

**Comment by billnbell** [comment]
Yeah I tried to remove and merge everything, but for some reason it shows 24 commits, for 1 commit.

Weird!!


From: Vojtech Novak ***@***.***>
Date: Monday, March 22, 2021 at 6:27 AM
To: react-native-datetimepicker/datetimepicker ***@***.***>
Cc: William Bell ***@***.***>, Mention ***@***.***>
Subject: Re: [react-native-datetimepicker/datetimepicker] Fix for RN spinner (#416)

hello @billnbell<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbillnbell&data=04%7C01%7C%7Ce3f99360343445820b2c08d8ed2dd28d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637520128345651824%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CR2vkTj5h6KFVaTSQcXhvO43gmv45ToayPuvr30JRLo%3D&reserved=0> would you mind cleaning up the git history a little so it's clear I'm not merging 24 commits but just 1 commit? Thank you! 👍

**Comment by billnbell** [comment]
Please delete this PR for the new one.

**Comment by billnbell** [comment]
New one is clean

**Pull request closed without merging**
