### PR TITLE
Add missing countdown in RCT_ENUM_CONVERTE

### PR DESCRIPTION
**Pull request by Nasseratic**
# Summary
After upgrading react native to `0.72.3` the countdown mode stopped working and was fallback to time mode. My guess is that react native changed how `RCT_ENUM_CONVERTER` works.
Adding `countdown` to the enum fixed the issue.

## Test Plan
Try passing countdown to mode prop 

| Before | After the fix |
|--------|--------|
|  |  | 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [ ] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
thank you! 🙂

**Comment by vonovak** [comment]
@Nasseratic I see you've been responding to some issues here, appreciate it! Are you on discord? If you're interested, perhaps we could chat about if / how you can / want to help out with maintaining the library, ask questions and etc? 🙂

**Comment by Nasseratic** [comment]
@vonovak Yes I am on Discord my username is `nasseratic`. Yes would love to chat and help with maintaining as much as I can :)

**Comment by vonovak** [comment]
@Nasseratic can you please check your discord? I sent you a friend request a week ago or so :)

thank you!

**Pull request merged**
