### PR TITLE
Feat/spinner hide fields

### PR DESCRIPTION
**Pull request by luisflorido**
# Summary
According to this PR #200 (@sarahshuffle) asks for show only month and year, i think it is a great possibility when you need just month or just year on a spinner. I maded this for Android and if someone can help to implement this on iOS will be a great feature.

## Test Plan

android_spinner_hide_1
android_spinner_hide_2

### What's required for testing (prerequisites)?
- Android environment

### What are the steps to reproduce (after prerequisites)?
- Run project on android and set a date -> spinner and you have spinner hide props

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)
- [X] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
Hello and thank you for the PR!

As you can tell, the CI is currently broken. I'm going to fix it and then get to review your PR. Thank you! :)

**Comment by felippepuhle** [comment]
@luisflorido @vonovak any chances we can get this merged in and released soon? I can help you with that

**Comment by vonovak** [comment]
@felippepuhle Thanks for expressing your interest. I'm a little hesitant to merging this since the next thing people will ask for is iOS support for the feature, and iOS will likely require a completely new view to support this (UIDatepicker does nto support this). How do you plan to implement this on iOS for your use case?
Thanks

**Comment by felippepuhle** [comment]
> @felippepuhle Thanks for expressing your interest. I'm a little hesitant to merging this since the next thing people will ask for is iOS support for the feature, and iOS will likely require a completely new view to support this (UIDatepicker does not support this). How do you plan to implement this on iOS for your use case? Thanks

Ohhh I see your point now! yeah in that case it's probably better to keep the consistency across platforms, for my specific use case I'll probably build a custom picker as year + month picker is a simple thing... thanks clarifying it!

**Comment by vonovak** [comment]
hello again, 
given that there does not appear to be large demand for this and given the explanation I gave above, I decided against merging this.
I am sorry for the time spent on this didn't go into fruition but as mentioned, implementing a picker only for year and month is not a complicated task. Also, in the linked issue (#200) I asked for consulting maintainers before implementing to avoid such situation.

So thanks everyone involved an I'm closing this.

**Pull request closed without merging**
