### PR TITLE
fix android e2e test

### PR DESCRIPTION
**Pull request by luancurti**
# Summary
The `android.widget.DatePicker` is disappearing from the screen after 3 seconds and the e2e tests are failing

## Test Plan

e2e tests are running ok

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅      |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)
- [x] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by vonovak** [comment]
> The android.widget.DatePicker is disappearing from the screen after 3 seconds and the e2e tests are failing

@luancurti why is it disappearing after 3 seconds when it should disappear after 6? https://github.com/react-native-datetimepicker/datetimepicker/blob/e7817caa6ae28d5425fc0122099ddc874f24de81/example/App.js#L205

I believe it's some sort of flakiness that just happens in e2e testing, but it does indeed look like this change makes the test more stable... So I'm for merging, just wondering why you think it disappears after 3 seconds..?

**Review by vonovak — APPROVED** [review]

**Comment by vonovak** [comment]
let's merge and see

**Comment by luancurti** [comment]
> > The android.widget.DatePicker is disappearing from the screen after 3 seconds and the e2e tests are failing
> 
> @luancurti why is it disappearing after 3 seconds when it should disappear after 6?
> 
> https://github.com/react-native-datetimepicker/datetimepicker/blob/e7817caa6ae28d5425fc0122099ddc874f24de81/example/App.js#L205
> 
> I believe it's some sort of flakiness that just happens in e2e testing, but it does indeed look like this change makes the test more stable... So I'm for merging, just wondering why you think it disappears after 3 seconds..?

I don't know, I just run in Android Emulator and sometimes it disappears after 3 seconds 🤯, we need to investigate

**Pull request merged**
