### PR TITLE
fix: dismiss android datepicker dialog upon unmount

### PR DESCRIPTION
**Pull request by vonovak**
# Summary
this replaces #326 because the author did not allow to push into his branch

I figured it was easier to do this separately than by reviews

original description:

> This commit makes the behavior of the android datetimepickers more in
line with other controlled components in react, where unmounting the
component actually dismisses the ui widget as well.

I also think it might be useful to have a way to dismiss android dialogs from JS and this will expose that possibility. The api will be documented later after we change the api of the android picker to an imperative one, as outlined in https://github.com/react-native-datetimepicker/datetimepicker/pull/327#issuecomment-723160992

## Test Plan

run demo app, click the "Show and dismiss picker!" button

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)
- [x] I have added automated tests, either in JS or e2e tests, as applicable

### CODE REVIEW

**Comment by luancurti** [comment]
@vonovak I think we can add docs for `dismiss` method on `readme`. WDYT?

**Comment by vonovak** [comment]
@luancurti in order to expose that as the public api, we'd need to expose a bunch of other things as well, and I think it'll be better to leave that for another PR.

**Review by luancurti — APPROVED** [review]
LGTM

**Pull request merged**
